(MINOR) Hide User assertions from public SDK
contentauth/c2pa-rs pull request #141
Opened 2022-09-30 15:08 UTC by gpeacock

## Changes in this pull request
Remove User, UserCbor and Uuid assertions from the public SDK
Use add_labeled_assertion instead.
## Checklist
- [ ] This PR represents a single feature, fix, or change.
- [ ] All applicable changes have been documented.
- [ ] Any `TO DO` items (or similar) have been entered as GitHub issues and the link to that issue has been included in a comment.

2022-09-30 17:48 UTC, scouten-adobe commented on sdk/src/manifest.rs
> +    /// use c2pa::{create_signer, Manifest, SigningAlg,};
Extra comma here shouldn't be necesary.

2022-09-30 17:49 UTC, scouten-adobe requested changes
Looks good. I'd like to see something in the README (breaking changes since 0.14.0 to call attention to how anybody using the now-private interface should update their code.

2022-09-30 19:44 UTC, dkozma approved these changes
LGTM after fixing @scouten-adobe 's comment

2022-09-30 23:11 UTC, gpeacock commented on sdk/src/manifest.rs
> +    /// use c2pa::{create_signer, Manifest, SigningAlg,};
removed

2022-10-01 00:53 UTC, scouten-adobe reviewed
I think any developer relying on existing functionality could feel pretty frustrated upon taking this upgrade and not having an obvious guide to how to migrate.

I'll grant that an upgrading guide isn't particularly common, but I've seen some crates that do this (for example, https://github.com/rust-random/rand#versions) and I think it's a pattern worth adopting.

FWIW I do this in the XMP Toolkit crate: https://github.com/adobe/xmp-toolkit-rs#breaking-changes-in-0x-series

What you've added in the changelog says that there is something that is breaking, but isn't particularly helpful in guiding any developer affected by the change toward a resolution of their problem.

I won't give this a :+1: without a guide, but I'll remove my change request.

2023-07-13 21:34 UTC, gpeacock commented
Updated readme and pulled in the latest changes. The example using the User assertion has been replaced the an an example of using a custom struct and add_labeled_assertion

2023-07-13 22:02 UTC, merged