(MINOR) Resource format and is_parent / relationship changes
contentauth/c2pa-rs pull request #202
Opened 2023-03-07 23:05 UTC by gpeacock

## Changes in this pull request
Change the resourceReference to use `format `instead of `content_type` to keep it consistent with the use of `format `elsewhere. This impacts the internal format of manifest and ingredient thumbnail values.

Change the ingredient field `is_parent` into `relationship` with a enum value of `parentOf`, or `componentOf` to align with the spec and allow for proposed additional relationship values such as `inputTo`. This does not impact the API directly but it will change the format of JSON ingredients for reports and input.

## Checklist
- [ ] This PR represents a single feature, fix, or change.
- [ ] All applicable changes have been documented.
- [ ] Any `TO DO` items (or similar) have been entered as GitHub issues and the link to that issue has been included in a comment.

2023-03-07 23:42 UTC, scouten-adobe requested changes
I was studying this PR closely to see if a `(MINOR)` tag was missing and I see now that the build automation flagged it as such.

Also, where is this serialized? I'd like to see a test showing the intended new serialization.

2023-03-08 00:31 UTC, gpeacock commented
@scouten-adobe There are serialized JSON tests in ResourceStore and Manifest. I had to update those unit tests to work with these changes, since the caught the changes.
look for MANIFEST_JSON

2023-03-09 18:38 UTC, scouten-adobe approved these changes

2023-03-09 19:12 UTC, scouten-adobe commented
@gpeacock as discussed in Slack, go ahead and use admin override to merge this PR. I'm unable to fix the (MINOR) version check to pay attention to the PR title at this time, but the right thing will happen when you squash and merge.

2023-03-10 19:20 UTC, merged