Gpeacock/tool config
contentauth/c2pa-rs pull request #28
Opened 2022-05-31 06:21 UTC by gpeacock

## Changes in This Pull Request
35b54e5: Rework c2patool configuration

## Checklist
- [ ] This PR represents a single feature, fix, or change.
- [ ] All applicable changes have been documented.
- [ ] Any `TO DO` items (or similar) have been entered as GitHub issues and the link to that issue has been included in a comment.

2022-05-31 18:23 UTC, scouten-adobe requested changes
A couple of quick comments here and ~~I'd also like to make some proofreading and style changes in this PR. Will do after meetings (likely after 1pm Pacific).~~

2022-05-31 23:05 UTC, gpeacock commented on Cargo.toml
> +members = ["sdk", "c2patool", "make_tests"]
I'm not crazy about a three part command line name. I actually think make_tests is very descriptive - it makes tests.

2022-05-31 23:06 UTC, gpeacock commented on Cargo.toml
> +members = ["sdk", "c2patool", "make_tests"]
It could be make_assets or make_images

2022-05-31 23:43 UTC, scouten-adobe commented on Cargo.toml
> +members = ["sdk", "c2patool", "make_tests"]
IMHO it doesn't make the _entire_ test; of the above, I'd probably be most happy with make_assets.

2022-06-01 00:44 UTC, scouten-adobe commented
Based on Slack discussion just now, I'm withdrawing my request to edit doc comments in c2patool.

I still would like to see the `make_tests` name changed.

2022-06-02 16:25 UTC, scouten-adobe approved these changes

2022-06-02 16:44 UTC, merged