Export `AssertionDefinition` in public API
contentauth/c2pa-rs pull request #522
Opened 2024-07-23 14:10 UTC by ok-nick

## Changes in this pull request
Export `AssertionDefinition` in public API.

## Checklist
- [x] This PR represents a single feature, fix, or change.
- [x] All applicable changes have been documented.
- [x] Any `TO DO` items (or similar) have been entered as GitHub issues and the link to that issue has been included in a comment.

2024-07-29 15:12 UTC, gpeacock commented
This should be ok. I'd updated this structure so that we can support CBOR based assertions better. Previously the definition at this level only supported JSON. It's a little weird because the default assertion encoding is CBOR when passing a full definition in JSON. Generally that's fine since CBOR is a superset of JSON. But if you call the APIs directly you can add an assertion with CBOR specific encoding.

2024-07-29 15:14 UTC, gpeacock requested changes
Do we have an integration test that shows these can be used outside the crate? We should add something for that.

2024-07-29 19:45 UTC, ok-nick commented
@gpeacock These structs specifically or constructing a builder using Rust structs as a whole? It'd be a good idea to implement it for all structs either way, I can send a separate PR implementing that.

2024-08-07 04:31 UTC, gpeacock approved these changes

2024-08-07 04:31 UTC, merged