feat: Claim v2
contentauth/c2pa-rs pull request #707
Opened 2024-12-04 13:33 UTC by mauricefisher64

## Changes in this pull request
Support V2 Claim processing

## Checklist
- [x] This PR represents a single feature, fix, or change.
- [x] All applicable changes have been documented.
- [ \x] Any `TO DO` items (or similar) have been entered as GitHub issues and the link to that issue has been included in a comment.

2024-12-04 17:01 UTC, scouten-adobe commented on sdk/src/time_stamp.rs
> +pub(crate) fn get_timestamp_signed_data(data: &[u8]) -> Result<Option<SignedData>> {
FYI once PR #696 lands, this function will be known as `c2pa_crypto::time_stamp::signed_data_from_time_stamp_response`.

2024-12-04 17:16 UTC, scouten-adobe commented on sdk/src/time_stamp.rs
> +pub(crate) fn timestamptoken_from_timestamprsp(ts: &[u8]) -> Option<Vec<u8>> {
When #696 lands, this should be replaced with the following sequence:

```rust
let ts_resp = c2pa_crypto::time_stamp::TimeStampResponse::parse_der(ts)?;
let ts_token = ts_resp.time_stamp_token()?;
```

2024-12-04 17:38 UTC, scouten-adobe commented on sdk/src/time_stamp.rs
> +    let Ok(Some(sd)) = get_timestamp_signed_data(ts) else {
These changes are now mirrored in #696.

2024-12-05 00:41 UTC, scouten-adobe commented on sdk/src/time_stamp.rs
> +pub(crate) fn get_timestamp_signed_data(data: &[u8]) -> Result<Option<SignedData>> {
Nvm. That wasn't quite accurate, but I fixed that up when I did the merge.

2024-12-05 00:41 UTC, scouten-adobe commented on sdk/src/time_stamp.rs
> +pub(crate) fn timestamptoken_from_timestamprsp(ts: &[u8]) -> Option<Vec<u8>> {
Fixed it up in merge.

2025-01-24 00:12 UTC, tmathern commented on cli/src/tree.rs
> +            let title = ingredient.title().unwrap_or("Untitled");
Is `Untitled` a default that will be reused everywhere?

2025-01-24 00:12 UTC, tmathern commented on cli/src/tree.rs
> +                    format!("Asset:{title}")
```suggestion
                    format!("Asset: {title}")
```

2025-01-24 00:12 UTC, tmathern commented on docs/release-notes.md
> +You are still be able to use the deprecated API by enabling the `v1_api` feature; for example:
```suggestion
You will still be able to use the deprecated API by enabling the `v1_api` feature; for example:
```

2025-01-24 00:12 UTC, tmathern commented on docs/usage.md
> +You are still be able to use the deprecated API by enabling the `v1_api` feature; for example:
```suggestion
You will still be able to use the deprecated API by enabling the `v1_api` feature; for example:
```

2025-01-24 00:12 UTC, tmathern commented on internal/crypto/src/time_stamp/mod.rs
> +// ^^ TO REVIEW: Does this need to be public after refactoring?
Would be nicer if it's not public?

2025-01-24 00:12 UTC, tmathern commented on sdk/src/assertion.rs
> +        self.version.unwrap_or(1)
Nitpick: Maybe make the "default" or "fallback" version a constant to check against?

2025-01-24 00:12 UTC, tmathern commented on sdk/src/assertions/actions.rs
> +        //"c2pa.actions.v2"
? Leftover?

2025-01-24 00:18 UTC, tmathern commented on sdk/src/error.rs
> +    VersionCompatibility(String),
If it's `VersionCompatibility(String)`, don't we want the string params also displayed into the error text?

2025-01-24 00:19 UTC, tmathern approved these changes

2025-01-24 00:38 UTC, scouten-adobe commented on cli/src/tree.rs
> +                    format!("Asset:{title}")
This appears inconsistent with the format statement at line 39 above.

2025-01-24 00:41 UTC, scouten-adobe commented on docs/usage.md
> +The new api is now enabled by default, the `unstable_api` feature is no longer used.
Please capitalize API consistently.

2025-01-24 00:48 UTC, scouten-adobe commented on internal/crypto/src/time_stamp/mod.rs
> +// ^^ TO REVIEW: Does this need to be public after refactoring?
Even better. We can delete it completely. Nobody uses it any more. (I've just submitted a commit to the branch.)

2025-01-24 00:52 UTC, crandmck requested changes

2025-01-24 00:52 UTC, crandmck commented on docs/release-notes.md
> +You are still be able to use the deprecated API by enabling the `v1_api` feature; for example:
Grammar: `You can still use the deprecated API....`

2025-01-24 00:52 UTC, crandmck commented on docs/usage.md
> +The new api is now enabled by default, the `unstable_api` feature is no longer used.
Also, this is a comma splice. S/be:

The new API is now enabled by default. The `unstable_api` feature is no longer used.

2025-01-24 00:52 UTC, crandmck commented on docs/usage.md
> +You are still be able to use the deprecated API by enabling the `v1_api` feature; for example:
I'd prefer: 
To use the deprecated v1 API, enable the `v1_api` feature; for example:

2025-01-24 00:56 UTC, scouten-adobe commented on sdk/Cargo.toml
> +c2pa = { path = ".", default-features = false }
Does this even need to be here at all any more?

2025-01-24 01:04 UTC, scouten-adobe commented on sdk/src/claim.rs
> +    // structure is not the Claim form the spec but an amalgamation that allows us to represent any version
form -> from

2025-01-24 01:09 UTC, scouten-adobe commented on sdk/src/claim.rs
> +                                    .map_err(|_err| Error::AssertionEncoding(_err.to_string()))?;
Please rename `_err` to `err` now that we're actually using the value.

2025-01-24 01:10 UTC, scouten-adobe commented on sdk/src/claim.rs
>      pub fn assertion_label_from_link(assertion_link: &str) -> (String, usize) {
@scouten-adobe continue review from here (probably tomorrow

2025-01-24 01:11 UTC, scouten-adobe reviewed
I ran out of time to review – please hold until I can review further.

2025-01-24 07:36 UTC, gpeacock commented on cli/src/tree.rs
> +            let title = ingredient.title().unwrap_or("Untitled");
good question. I don't think we have a UI call on that, but this is only for the tree view in c2patool.

2025-01-24 07:37 UTC, gpeacock commented on cli/src/tree.rs
> +                    format!("Asset:{title}")
I think it is best to keep fewer changes at least for now.

2025-01-24 07:49 UTC, gpeacock commented on sdk/Cargo.toml
> +c2pa = { path = ".", default-features = false }
good call, it isn't. I removed it.

2025-01-24 07:54 UTC, gpeacock commented on sdk/src/assertions/actions.rs
> +        //"c2pa.actions.v2"
thanks - removed

2025-01-24 17:25 UTC, gpeacock commented on docs/usage.md
> +You are still be able to use the deprecated API by enabling the `v1_api` feature; for example:
going with Rand's recommendation

2025-01-24 17:51 UTC, gpeacock commented on sdk/src/error.rs
> +    VersionCompatibility(String),
added the string

2025-01-27 18:58 UTC, scouten-adobe requested changes

2025-01-27 18:58 UTC, scouten-adobe commented on sdk/src/assertion.rs
> +    FieldDecoding { expected: String },
Can we rename this to something like `MissingField(String)`?

2025-01-27 18:58 UTC, scouten-adobe commented on sdk/src/assertions/ingredient.rs
> +            _ => Err(serde::ser::Error::custom("Ingredient serializer not found")),
Suggest for this either (a) making `self.version` an enum with the three allowed versions specifically enumerated (and thus impossible to get into this error situation), or (b) making the error message state that an unrecognized version was found.

2025-01-27 18:58 UTC, scouten-adobe commented on sdk/src/claim.rs
> +    pub fn assertion_typ(&self) -> ClaimAssertionType {
Typo: Should be `assertion_type`

2025-01-27 18:58 UTC, scouten-adobe commented on sdk/src/claim.rs
> +            self.assertion, self.instance, self.typ
Heading into a meeting. Will resume review from here.

2025-01-27 20:27 UTC, scouten-adobe commented on sdk/src/manifest.rs
>      #[cfg(feature = "file_io")]
Not a blocker, but I think these could be coalesced into:

```
#[cfg(all(feature = "file_io", feature = "v1_api"))]
```

2025-01-27 20:27 UTC, scouten-adobe commented on sdk/src/openssl/openssl_trust_handler.rs
> +// Copyright 2022 Adobe. All rights reserved.
Not a blocker, but I'd prefer that we make this part of the `c2pa_crypto` API surface rather than duplicating the file here.

2025-01-27 20:27 UTC, scouten-adobe commented on sdk/src/store.rs
> +    #[allow(dead_code)]
Consider adding a note explaining why the `dead_code` bypass is needed and when/if we might be able to remove it.

2025-01-27 20:27 UTC, scouten-adobe commented on sdk/src/store.rs
> +    VersionFailure,
Consider naming this something like `UnsupportedVersion` or `UnsupportedFeature`. If it's about features, maybe a string describing what feature isn't supported.

2025-01-27 20:27 UTC, scouten-adobe commented on sdk/src/validation_results.rs
> +    pub fn validation_errors(&self) -> Option<Vec<ValidationStatus>> {
Same API design comment as earlier. Consider changing these `Vec` responses to `Iter` so you're not binding yourself to an underlying implementation.

2025-01-27 20:28 UTC, scouten-adobe approved these changes
Several things to consider still, but no blockers at this point.

2025-01-27 20:48 UTC, gpeacock commented on sdk/src/assertion.rs
> +    FieldDecoding { expected: String },
The field could be there but in the wrong format, such as being an array or number rather than an object. MissingField would be incorrect in that case.

2025-01-27 20:50 UTC, gpeacock commented on sdk/src/manifest.rs
>      #[cfg(feature = "file_io")]
Since I'm planning to rip out the v1 api entirely in the not to distant future, I've opted to not overly integrate this. But point taken.

2025-01-27 20:53 UTC, gpeacock commented on sdk/src/assertion.rs
> +    FieldDecoding { expected: String },
Perhaps we could get more clear about the type that was expected.

2025-01-27 20:57 UTC, gpeacock commented on sdk/src/claim.rs
> +                let ac = Actions::from_assertion(&assertion)?;
In this case it can't entirely be moved since there can be multiple actions assertions, and the rule is that the first action in the first actions assertion must be something. That can only be determined at the claim level, knowing about all the assertions.

2025-01-27 21:19 UTC, gpeacock commented on sdk/src/validation_results.rs
> +    pub fn validation_errors(&self) -> Option<Vec<ValidationStatus>> {
This is only needed internally so I made it crate private

2025-01-27 21:35 UTC, gpeacock commented on sdk/src/claim.rs
> +    pub fn created_assertions(&self) -> &Vec<C2PAAssertion> {
The claim API is not made public, so this would not be a blocker.

2025-01-27 21:55 UTC, gpeacock commented on sdk/src/store.rs
> +    VersionFailure,
done

2025-01-27 21:56 UTC, gpeacock commented on sdk/src/store.rs
> +    #[allow(dead_code)]
changed to being marked as a v1 feature

2025-01-27 23:43 UTC, merged